# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetCommand@2
  inputs:
     command: 'restore'
     restoreSolution: '**/*.sln'
     feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '2b0aa5c8-66c3-4fb7-9061-b7b308b01d7e'
    
- task: ArtifactoryDotnetCore@1
  inputs:
    command: 'restore'
    artifactoryService: 'nuget-test'
    targetResolveRepo: 'test-baget-nuget-remote'
    rootPath: '**/*.sln'