# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
  
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '0215435a-cb98-4b9a-a3fd-8f1eab664930'  
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'baget'
    command: 'jfrog rt dotnet restore'
