node {
    def server
    def buildInfo
    def rtMaven
    
    stage ('Clone') {
        git url: 'https://github.com/ganavikumar/project-examples.git'
        
    }
 
    stage ('Artifactory configuration') {
        // Obtain an Artifactory server instance, defined in Jenkins --> Manage Jenkins --> Configure System:
        server = Artifactory.server 'maven-cloud'

        rtMaven = Artifactory.newMavenBuild()
        rtMaven.tool = 'maven-test' // Tool name from Jenkins configuration
        rtMaven.deployer releaseRepo: 'clous-libs-release-local', snapshotRepo: 'clous-libs-snapshot-local', server: server
        rtMaven.resolver releaseRepo: 'clous-libs-release', snapshotRepo: 'clous-libs-snapshot' , server: server
        rtMaven.deployer.deployArtifacts = true // Disable artifacts deployment during Maven run

        buildInfo = Artifactory.newBuildInfo()
    }
 
    stage ('Test') {
        rtMaven.run pom: 'maven-examples/maven-example/pom.xml', goals: 'clean test'
    }
        
    stage ('Install') {
        rtMaven.run pom: 'maven-examples/maven-example/pom.xml', goals: 'install', buildInfo: buildInfo
    }
 
    stage ('Deploy') {
        rtMaven.deployer.deployArtifacts buildInfo
    }
        
    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}
